### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by jejjohnson** [earthpulse/pytorch_eo#1]
Hi,

First of all, I really wanted to thank you all for your efforts in this repo. It's super useful and amazing to see dataloaders for new/standard EO Datasets. And the fact that it uses PyTorch and PyTorch-Lightning just makes development so much easier!

I wanted to ask what were the guidelines for contributing? I really liked what you all did for EuroSat and I am interested in replicating that format for some other datasets. In particular I was thinking BigEarthNet as well as possible some open-source hyperspectral datasets.

Do you all plan to have some plans for contributions from the public? 

Thanks again!

**Comment by earthpulse** [comment]
Hi ! Glad to hear you like it :) The project is en early stages and we plan to start adding things as soon as I have some time.

One of the possible contributions is more datasets, following the example of EuroSAT (download, process and ready to train models). I was going to add BigEarthNet soon, so I think is a very good idea if you want to do it.

Just fork the repo, create a new branch called big-earth-net (or something similar), add the code and a example (a notebook is enough) and then make a pull request. We will review it, suggest modifications and add it to the main repo when everything looks ok.

We will try to add some guidelines for contirbutins ASAP.

We can use this threat to continue the conversation, although I suggest making a new issue for the BigEarthNet dataset so we can discuss the approach.

**Comment by juansensio** [comment]
Closing the issue since BigEarthNet is already available !
