### ISSUE TITLE
Common goals!

### ISSUE THREAD

**Issue by calebrob6** [earthpulse/pytorch_eo#2]
Hi earthpulse folks!

It looks we (mainly @adamjstewart, @isaaccorley and I) are working on a similar package to you all at https://github.com/microsoft/torchgeo. We're trying to implement a production quality package that includes dataloaders for common earth observation datasets (largely building off of @isaaccorley's massive effort at https://github.com/isaaccorley/torchrs), generic composable dataloaders for different types of remotely sensed imagery, and a pytorch lightning based training script for generating benchmark results / pretrained model weights. I was wondering if you all have any interest in contributing?

Best,
Caleb

**Comment by earthpulse** [comment]
Thanks for the hint ! We will look into it and if we see that torchgeo fits our needs we would definetly contribute and avoid duplicate projects.

**Comment by earthpulse** [comment]
After careful evaluation we concluded that we are going to move on with our plans and development roadmap for PytorchEO, mainly due to the fact that we are planning to integrate the rest of services that we offer and the library will be a key piece in our tech stack.
